maths/moodle-qtype_stack

- stack/cas/castext/castext.peg.inc
- stack/cas/castext/castextparser.class.php
Helps with very large CASTEXTs, basically STACK_3.4S-branch could not go forward without this.
Also important for other uses as PHP-recurse limit is typically 100 and if you place hundred or so CAS-variables into to the CASTEXT in certain way, you will cause that recursion to explode.
> Fixed the normalization of the parse-tree to be bit less recursive.

- doc/en/CAS/Optimising_Maxima.md
the target link for the Lisp Implementations appears to have been domain squatted. I've pointed it to the SourceForge homepage for Maxima. YMMV as to whether this is the best target. You can check the old target: http://maxima-project.org/wiki/index.php?title=Lisp_implementations
> corrected broken link to Lisp implementations

- lang/en/qtype_stack.php
added supporting text pointing out that an optimised image of maxima would not pick up libraries entered in the field "Load optional Maxima libraries:" (qtype_stack | maximalibraries )
> clarified descriptive text for qtype_stack | maximalibraries in qtype_stack.php

- doc/en/CAS/Optimising_Maxima.md
I found that the statistics packages weren't loaded. This is because I had saved an image without the packages loaded. When I loaded them the healthcheck complained about incompatibility. The fix is to load all the required libraries. Tested with maxima 5.36.0 built from source.
> clarified documentation about optimising maxima

- stack/potentialresponsetree.class.php
- stack/utils.class.php
Inspired by my comment in maths/moodle-qtype_stack#183, this adds functions `stack_utils::rational_approximation` and `stack_utils::fix_to_continued_fraction`.
Instead of just rounding scores >= 0.9999999 up to 1, this finds a rational approximation to the score which agrees to 5 d.p. (need to decide the best number of d.p.)
This rounds numbers which are close to 1 up to 1, but also rounds e.g. 0.33333 to 1/3 (or as close as you can get to 1/3 in a float)
This needs unit tests, but I don't know how to write those.
It might make sense to replace `stack_utils::fix_approximate_thirds` with `fix_to_continued_fraction` - as far as I can see, that's only used on penalties at the moment.
> take continued fraction approximation of the score at the end of a PRT

- stack/cas/castext/castext.peg.inc
- stack/cas/castext/castextparser.class.php
- tests/parser_test.php
Use of a ```define``` inside ```if-elif-else``` caused some unexpected behaviour, now fixed to better match the typical behaviour expected from ```if-elif-else``` type of an structure.
> Bugfix for if-elif-else.

- stack/input/inputbase.class.php
This item implements a fix that shows the validation of the equation correctly in realtime without the need for clicking the 'Check' button to do the validation.
> Always filter equation validation

- stack/cas/castext/castext.peg.inc
- stack/cas/castext/castextparser.class.php
- tests/castext_test.php
- tests/parser_test.php
Inconvenient logic failure present in a case that was not tested. Also fixes an error not yet reported relating to DOM-tree corruption when handling if-elif-else constructs that were directly next to each other.
#309
> Fix logic error in if-elif-else-blocks else branch.

- questiontype.php
Before this change, on the Edit question form, inputs (and PRTs) were
shown in the order they appeared in the question text, while on the
Question tests page, they appeared in alphabetical order.
Not a terrible thing, but nicer to keep it consistent.
It seemed safest to get the order right when the question is
intitialised, even though this is a small amount of unnecessary work
in some cases. I don't think it is significant.
> Always show question parts in the same order

- stack/cas/casstring.class.php
Breaks no tests and is trivial enough.
> Add special character rendering as escapes to help with problems like #321.

- doc/en/CAS/Optimising_Maxima.md
These changes have been tested in CENTOS 6/7 and seem to resolve the stack page exception problem that appeared.
> Remove libs from SBCL instructions

- stack/cas/cassession.class.php
- stack/cas/castext.class.php
I think this is the required fix:
* We should use preg_replace to strip the \mbox{ ... } so that it does not mangle strings that don't match teh expected pattern.
* We should always string <html> ... </html> wrappers. I cannot imagine any case when we would want them in the output.
> Fix display CAS text clean-up #340

- stack/input/algebraic/algebraic.class.php
- stack/input/equiv/equiv.class.php
- stack/input/matrix/matrix.class.php
- stack/input/numerical/numerical.class.php
- stack/input/singlechar/singlechar.class.php
- stack/input/string/string.class.php
- stack/input/textarea/textarea.class.php
- stack/input/units/units.class.php
- tests/input_algebraic_test.php
- tests/input_equiv_test.php
- tests/input_matrix_test.php
- tests/input_numerical_test.php
- tests/input_singlechar_test.php
- tests/input_string_test.php
- tests/input_textarea_test.php
- tests/input_units_test.php
I was demoing STACK on an iPad yesterday, and it was a real pain because if you tried to type x + 1, it automatically changed it to X + 1. (It upper-cases the first character of input by default.)
Fortunately, HTML5 provides a way to tame this behaviour, which is what I implement here. See https://caniuse.com/#search=spellcheck and https://github.com/Fyrd/caniuse/issues/1729.
However, I have not yet tested this on an iPad to verify that it acutally has the desired effect, and it is too late this evening. I just wanted to get the code written. I have run the unit tests, and they pass.
> Improve input usability on iPads, etc.

- stack/maxima/assessment.mac
- stack/maxima/stackmaxima.mac
Calculation of MAXIMA_VERSION_NUM improved to avoid problems with nightly builds of maxima by ubuntu maintainers, s. issue #398.
> Maxima nightlies

- cli/clearcascache.php
This is something we want at the OU to help automate our releases.
Obviously, the cache is purged automatically as part of the STACK upgrade. However, our CAS cache can get very large (e.g. 350,000 plot files in Moodledata) and deleting them all takes many tens of minutes. We would like the option to purge the chache in advance, so we don't have to wait all those minutes while Moodle is in maintenance mode. Hence this script.
> Command-line script to clear the CAS cache

- styles.css
Whe a STACK question is in an iframe, which might happen if you are
using https://moodle.org/plugins/filter_embedquestion, then it is a reall bad user-experience if you
can navigate to the 'Question tests & deployed versions' page.
Therefore, we hide the link in that case.
For embedded questions, authors will have to access the question tests
via the question bank.
(We just did a similar change in our 'Pattern-match' question type, and I thought I should submit the same change to STACK.)
> Hide the 'Question tests' link in iframes

- doc/en/CAS/Numbers.md
- stack/basenoptions.class.php
- stack/input/inputbase.class.php
- stack/maxima/basen.lisp
- stack/maxima/basenfuncs.mac
OK, this is not the finished article, but I have been using it for a while now and it serves a purpose; here are the areas requiring further development, along with more testing:
1. The 'interpreted as' output in answer validation is pretty counter-intuitive, as it shows the function call wrapper (frombasen) used to process the students' answer.
2. Matrix handling; I have not fully tested whether the base N functions can be used in a matrix context and whether there is a way of making matrices more null friendly. This is important to me because it would allow the student enter working more easily and me to actually mark it.
3. Library functions; in presenting effective questions and answers I use a lorry load of helper definitions that do things like converting to from floating point …
> Iss317 - base N support (finally!)

- stack/input/algebraic/algebraic.class.php
- stack/input/equiv/equiv.class.php
- stack/input/numerical/numerical.class.php
- stack/input/string/string.class.php
- stack/input/textarea/textarea.class.php
- stack/input/units/units.class.php
- styles.css
Suggested fix for RTL mode, in which all math formulas need to be input in LTR mode (text directionality)
> Force math formulas input directionality to LTR, also in RTL mode.

- stack/maxima/stackmaxima.mac
When plotting an expression containing greater than and less than symbols, the generated HTML output is malformed, and part of the alt text of the img tag is displayed below the plot in the browser.
> Quote HTML entities in alt attribute.

- stack/maxima/stackstrings.mac
- stack/maxima/utils.mac
This fixes https://github.com/maths/moodle-qtype_stack/issues/674.  The function `ssubst(a,b,s)` generates an error if there are too many instances of `b` in `s`; this is a bug in Maxima (in some versions on some platforms, at least).  This comes into play if we have complex questions that generate generate LaTeX strings with many backslashes, for example.  So we change the functions `stackjson_stringify`, `str_to_html` and `str_to_js` to use `charlist` and `simplode` rather than `ssubst`.
> Refactor calls to ssubst

- doc/en/Authoring/Potential_response_trees.md
There was a missing `|` in table, making the rendering of table fail.
> Fix table in Potential_response_trees.md

- .github/workflows/deploy_website.yml
- doc/en/Developer/Website.md
- site_overrides/main.html
- site_overrides/partials/nav-item.html
This fixes the style issue with the online docs identified by @shinuito in maths/moodle-qtype_stack#713. One of the updates to mkdocs-material had, among other things, changed the names of some of its css styles. Because our implementation includes custom overrides of some of the material files, the website would not work until we referred to the new style names locally.
> Updates custom overrides of mkdocs-material files

- doc/en/Authoring/Answer_tests.md
Add note about using anchors in regular expressions in order to test against full equality as opposed to (sub-)pattern matching.
> Answer_tests.md (SRegExp): testing for equality

- doc/en/Authoring/Errors.md
This adds a short example to the docs, to explain one way to adapt code to suit the new validator.
> add an example of "potentially redefined in unclear substitutions"

- db/install.php
- doc/en/Developer/Unit_tests.md
- tests/fixtures/test_maxima_configuration.php
We were getting a problem with fatal errors on our CI server when trying to install Moodle including the STACK code on a system without Maxima.
This provides a way for people to avoid those fatal errors. It would help us if you are prepared to merge this. Thanks.
> Option to skip trying to build maxima-optimised when installing for test

- doc/en/Authoring/Answer_tests.md
Having more than one h1 on the page breaks the "table of contents" in the online docs https://docs.stack-assessment.org/en/Authoring/Answer_tests/
> Avoid reusing h1

- .github/workflows/moodle-ci.yml
- questiontype.php
- tests/behat/create_preview_edit.feature
- tests/behat/restore_demo.feature
Also, this gets all the Behat tests passing, and puts them back into the CI build properly. The other one with issues was the one that tested restore.
> Fix saving the deployed variants and question tests when a question is duplicated #880

- questiontestreport.php
Hi Chris,
The DB query in questiontestreport for Moodle 4.0 was fetching all the question attempts irrespective of the question id. Because of which, we were getting the below warning messages in the 'Basic question use report'. Have made the changes to fetch the question attempts considering all the question versions.
Could you please review the same?
Basic question use report:
Warning: Undefined array key 11 in <path>\question\type\stack\question.php on line 312
Warning: Undefined array key 10 in ...\question\type\stack\question.php on line 312
Thanks,
Anupama
> Fix questiontestreport DB query to fetch all attempts of all versions

- doc/en/Developer/Running_question_tests_other_site.md
- stack/bulktester.class.php
Hi Chris, 
Here is a small change to fix the 'Back' navigation URL on bulk test results page. Could you please review?
One of the PHPUnit test is failing, which is the same as the one failing on https://github.com/maths/moodle-qtype_stack/actions/runs/3970684491/jobs/6806699507. (If I figure out the fix for that then will create a new pull request)
Thanks, 
Anupama.
> Fix 'Back' navigation url on bulk test results page

- .github/workflows/moodle-ci.yml
- doc/docslib.php
- tests/castext_test.php
- tests/fixtures/test_base.php
- tests/mathsoutputtex_test.php
**Note**: This branch should resolve https://github.com/maths/moodle-qtype_stack/issues/720 and should be considered a "better" fix than https://github.com/maths/moodle-qtype_stack/pull/721 - as it allows tests to pass regardless of the specific Lisp compiler used to compile Maxima. Additionally it adds some misc CI and PHPUnit fixes.
**Background**
When using Maxima compiled under SBCL (which is used by [maximapool-docker](https://github.com/catalyst/maximapool-docker) for performance reasons), the CAS returns different values for scientific notation compared to Maxima compiled under GCL (which is what you get from Ubuntu/Debian's repositories). To see this; compare the results of the expression `scientific_notation(0.000000000001)` in Maxima compiled against GCL vs SBCL:
**GCL**
```` …
```
> Better normalise floats for cross compatibility between SBCL and GCL Maxima

- stack/input/inputbase.class.php
Hi Chris, 
We found some PHP deprecated error when updated to PHP 8.1. Hence have done a small change to fix the same in stack/input/inputbase.class.php. Could you please review?
I have done the change assuming that the minimum supported PHP version for STACK is PHP 7.4 or later. I hope that is OK.
Thanks,
Anupama.
> Fix PHP deprecated error in inputbase.class.php

- stack/mathsoutput/mathsoutputbase.class.php
Hi Chris,
Thanks for merging the fix for the earlier issue. We have seen one more PHP8.1 deprecation error related to str_replace in stack/mathsoutput/mathsoutputbase.class.php. Could you please review the fix?
Error:
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/moodle/question/type/stack/stack/mathsoutput/mathsoutputbase.class.php on line 89
Thanks,
Anupama
> Fix PHP8.1 deprecation error of str_replace in mathsoutputbase.class.php

- edit_stack_form.php
Hi Chris,
When we create/edit a Stack question, the Node and Standard feedback boxes seem to very small, of strictly one line. Changing the number of rows to two should increase the usability. (Also, we recently received a complaint by staff member regarding the feedback boxes being very small for some of the question types.)
Could you please review the patch? We assume this would be an useful change.
Thanks,
Anupama
> Increase Node and Standard feedback box sizes to two for usability

- doc/en/CAS/Inequalities.md
In chained inequalities, `EqualComAss` sees `and` and `nounand` as different things. Added a link to the propositional logic page where the distinction is explained.
The wording probably could be improved (and please correct me if I've misunderstood the whole issue), but this might be good to mention &ndash; this PR brought to you by several hours of debugging 😄 We had some exercises from 2020 that used `and`/`or` chained inequalities and `EqualComAss`, and that broke in a (long-due) STACK upgrade.
> Mention `nounand` and `nounor` in Inequalities doc

- renderer.php
Just experienced a rendering error in production, when attempting to resume a quiz preview. So far I was not able to cleanly reproduce this bug, but from what I gathered after a cursory look through the relevant code, I have an idea what the offending part is and how to fix it.
Here is the stack trace:
```
PHP message: Default exception handler: Fehler: Call to a member function get_rendered() on null Debug:
Error code: generalexceptionmessage
* line 209 of /question/type/stack/renderer.php: Error thrown
* line 193 of /question/type/stack/renderer.php: call to qtype_stack_renderer->stack_specific_feedback_errors_only()
* line 428 of /question/engine/renderer.php: call to qtype_stack_renderer->feedback()
* line 112 of /question/engine/renderer.php: call to core_question_renderer->outcome() …
```
> Fix rendering error when `$question->specificfeedbackinstantiated` is `null`

- doc/en/Installation/index.md
Installing maxima seems to have been an issue for a few people I have talked to lately. I updated the instructions to:
- present the installation via a package manager first (compiling from source seemed troublesome for some, but it was listed first)
- Point towards a commonly observed issue of the apache user not being able to run maxima (related issue linked)
- Instructions on how to check whether maxima is running fine and which version you're running
- Mention GoeMaxima/MaximaPool as alternatives.
I wonder if it is worth mentioning how to deal with dockerized Moodle setups? I don't know docker well enough to tell how to add STACK to a dockerized Moodle installation, but there are forks/setups to add some form of maxima to the setup:
- https://github.com/SvenKirschbaum/moodle-docker …
> Update Maxima installation instructions

- question.php
Hi Chris,
This a one more small fix to resolve the PHP8.1 deprecation error. Could you please review?
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/moodle/question/type/stack/question.php on line 1495
Thanks,
Anupama
> Fix PHP8.1 deprectation error for trim in question.php

- stack/mathsoutput/mathsoutputoumaths.class.php
This is something that is probably only of interest to the OU, but we just found this silly typo, so fixing it.
> Fix silly typo in oumaths filter integration

- doc/en/Authoring/Tidy_Tool.md
The images were interpreted like code and didn't preview.
> Fixing images

- questiontestreport.php
Hi Chris,
We have noticed some PHP deprecation errors related to PHP8.2 trim function on 'Analyze responses' page (questiontestreport.php). Could you please review the fix?
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/moodle/question/type/stack/questiontestreport.php on line 141
Thanks,
Anupama
> Fix PHP8.2 deprecated error for trim in questiontestreport.php

- adminui/caschat.php
- questiontestrun.php
Passing question variables, etc, as part of the URI when moving from the STACK dashboard to the CASchat page can cause an Apache error if the URI is too long.
There doesn't seem to be a good way of sending a POST request within Moodle that I can find, though. I tried a hidden form but that led to problems making the link look right. Instead, I've saved the quba (required for images showing on the dashboard anyway) and just passed the required info to load the question/attempt data on the CASchat page.
> Iss 1110 - CASchat URI too long

- questiontype.php
* Fix to Issue #929 in which default answer notes were not updating when performing question tidy to rename nodes.
* Also addressed analogous issue whereby default answer notes are not updating when performing question tidy to rename PRT.
> PRT tidy/answer note fix

- stack/graphlayout/graph.php
- tidyquestionform.php
Nodes are being display 1, 2, 11, 12, 3, 4, 5, 6, 7, 8, 9, 10
The node names are stored as strings but are always integers. However, the stored name is one less than the displayed name (and indeed any new name entered on the tidy page). This is the reason for the bizarre sort order - string sort on an integer combined with an off-by-one issue.
Unfortunately, as maths is being done on the names, adding a leading zero isn't going to work. The order of creation is also not preserved in the DB when a new version of the question is created as the new node records are saved in the mangled order.
Simplest solution is to sort nodes when they're requested.
> Iss 1041 - Sort PRT nodes for display

- backup/moodle2/restore_qtype_stack_plugin.class.php
I think this was triggered by an attempt to restore a really old and/or broken STACK question that was missing some fields. Previously with PHP 7, blank string fields would have been evaluated to 0 when attempting to perform maths but PHP 8 is more picky so the tidy up after importing such a question now fails. That tidy up is run on all restores so it keeps failing.
Casting to int forces evaluation to 0 and reinstates the old behaviour.
> iss-1120 - Fix restore of old questions causing all restores to fail

- stack/cas/connector.server.class.php
- stack/cas/connector.server_proxy.class.php
Hi Chris,
In some of the PHP versions, we see the following warning for stack questions with images. The function zip::getNameIndex() is returning the filename with a leading '/', thus setting the incorrect filepath, resulting in images not being displayed.
Error: 
Warning: file_put_contents(/efs/moodledata/stack/plots//stackplot-9809-1-3924935062-16894435.svg): Failed to open stream: No such file or directory in /var/www/html/moodle/question/type/stack/stack/cas/connector.server.class.php on line 86
Could you please review the fix?
Thanks,
Anupama
> Add trim to fix filename path returned by zip::getNameIndex function

- api/util/StackQuestionLoader.php
- tests/api_controller_test.php
- vle_specific.php
Fixes #1217 
Various PHP update issues:
- Fix creation of MathJax URL using empty string rather than null.
- Add question description to API question loader to avoid testing against null.
- Rewrite API tests to avoid using a generic mock class which was causing a type mismatch issue.
> Iss1217 - Failing tests in API on master

- question.php
- stack/questiontestresult.php
Hi Chris, 
We have noticed the below PHP deprecated error and a warning in some of our questions. Could you please review the fix for the same?
Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/moodle/question/type/stack/question.php on line 1572
Warning: foreach() argument must be of type array|object, null given in /var/www/html/moodle/question/type/stack/stack/questiontestresult.php on line 114
Thanks,
Anupama
> Fix PHP deprecated errors and warnings

- api/README.md
- api/docker/docker-compose.yml
I've put a pre-built image on Docker Hub and Sam Fearn has tried it out. This updates docs and docker-compose.yml to include the details. Could also be merged into master.
> api-build - Add info about pre-built Docker image

- settingslib.php
#1240 Here's another place where the file movement catches us, preventing TeX from appearing as an option.
> Iss1240 - Movement of filter files by Moodle

- tests/docslib_test.php
- tests/mathsoutputtex_test.php
Skip 2 asserts in Moodle < 4.1 as format_text ignores noclean option in 4.0.
> unit-test-fix - Skip certain asserts if Moodle < 4.1

- doc/en/CAS/STACK-Maxima_sandbox.md
- stack/maxima/stacklocallinux.mac
- stack/maxima/stacklocalwin.mac
- stack/maxima/testPlotLinux.wxm
- stack/maxima/testPlotWin.wxm
Adding a suggestion to configure the sandbox in the page STACK-Maxima_sandbox.
Use the maxima user dir, the access inside Maxima is independent from Windows or Linux
add the plot generation based on gnuplot.
- Config files for Windows and Linux (stacklocalwin.mac, stacklocallinux.mac)
- Testing: testPlotWin.wmx, testPlotLinux.wmx
Copy the files into 
Realization:
create directores `maxima_userdir/plots/` and `maxima_userdir/tmp/` and adjust variables `maxima_tempdir`, `IMAGE_DIR` and `URL_BASE`. On Windows gnuplot comes with Maxima, the path is obtained by `sconcat("c:/maxima-",build_info()@version,"/gnuplot/bin/gnuplot.exe")` 
To show the images, a file `test.html`in `maxima_userdir/plots/` is generated by a new command `add2HTML(string,fileappend)`. The file can be opened by …
> Extend STACK-maxima-sandbox: 

- doc/en/Authoring/Matching.md
- doc/en/Topics/Matching.md
- samplequestions/Parsons-examples.xml
- stack/input/parsons/parsons.class.php
- stack/maxima/contrib/matchlib.mac
- stack/maxima/proof.mac
This PR mainly addresses issues with using Parson's input type for test cases and matching problems.
- Fix automatic test case behaviour in the Parson's input for all types of use.
- Add cases for the grouping and matching style problems in the input type Maxima calls as these require different Maxima functions.
- Refactor of the Parson's input type to allow for (currently) three types "proof", "group", "match", corresponding to the Maxima answer functions `parsons_answer`, `group_answer`, `match_answer`. If further additions are made in this way to the Parson's block, then they only need to be added to the top two functions in the input type and the rest of the input type should work.
- Update documentation for matching problems.
- Update the Parson's sample questions.
> Correct Parson's input type for matching problems

- .github/workflows/moodle-ci.yml
- edit_stack_form.php
- tests/parsons_block_test.php
Expand div IDs to differentiate sections in the edit form when opening and closing.
Fix CI while I'm here:
- iframes use a couple of sneaky class parameters to control what's going on. These can persist between tests and need reset  if their value is essential to the test.
- Behat for the Moodle App is no longer compatible with PHP 7.4. I've raised an issue and switched off our checks for Moodle 4.1 for now.
#1287
> Iss1287 - Differentiate headers in edit form

- api/docker/docker-compose.dev.yml
- api/docker/docker-compose.yml
- doc/en/Developer/Releasing.md
I've done some testing and everything that previously worked in the API seems to be working.
I have access to more questions via the STACK library now, though, and the bad news is that the include block has never worked. I suggest we leave it for now and I fix it at a later date. Anyone using the API can build a new image from DEV if they really need the fix before our next release. The include block also works fine in the STACK library within Moodle.
> api-check - Update version numbers and docs

- api/emulation/MoodleEmulation.php
#1315 
This fixes issues with [[include]] and stack_include() in the API.
> iss1315 - Emulate Moodle download_file_content function in API

- stack/input/notes/notes.class.php
#1317 
The front end inserts '<br>' so we have to remove them again on the backend, the same as with textarea.
> iss1317 - Notes validation line break fix

- stack/input/dropdown/dropdown.class.php
a1a3fef introduced bugs that make some quizzes unusable.
I cannot reliably say, which types of questions exactly are affected, but I don't think this reproducibility is required in this case.
The bugs in question are simple `TypeError`s caused by wrong calls of the [`castext2_parser_utils::postprocess_mp_parsed`](https://github.com/maths/moodle-qtype_stack/blob/48bf1be50ac9321e3235f2169b965c5deaf077e1/stack/cas/castext2/utils.php#L140) and [`castext2_parser_utils::postprocess_parsed`](https://github.com/maths/moodle-qtype_stack/blob/48bf1be50ac9321e3235f2169b965c5deaf077e1/stack/cas/castext2/utils.php#L132) methods from within [`stack/input/dropdown/dropdown.class.php`](https://github.com/maths/moodle-qtype_stack/blob/48bf1be50ac9321e3235f2169b965c5deaf077e1/stack/input/dropdown/dropdown.c …
> Fix function call type errors in `stack_dropdown_input`

- templates/questionreport.mustache
Moodle no longer seems to have jQuery by default. Replacing usage with straight JS.
> Iss1342 - Fix analysis response page in Moodle 4.5

- tests/api_controller_test.php
This pull request resolves the unit test failures when the `mod_turnitintooltwo` plugin is installed.
Resolves issue https://github.com/maths/moodle-qtype_stack/issues/1355
1. Install https://github.com/turnitin/moodle-mod_turnitintooltwo (Optional)
2. With PHPUnit initialised, execute the following from your root Moodle directory:
`
php vendor/bin/phpunit question/type/stack/tests/api_controller_test.php
`
3. Confirm all tests pass.
> Update mock class names

- .github/workflows/moodle-ci.yml
- questiontestreport.php
- stack/questionreport.class.php
- templates/questionreport.mustache
- tests/behat/analysis.feature
- tests/behat/behat_qtype_stack.php
- tests/responseanalysis_test.php
#1393
- I've created a Behat test for the RA page in the hope of avoiding future problems like the jQuery issue.
- I've upped the number of repeats for Behat tests in the CI as this test and some of the App specific ones are struggling if GitHub is tired. (In this one, it's somehow possible to load the analysis page before the student's response has been recorded if things are running slowly.)
- URLs should be fixed.
- Including quizzes where the question is included as part of a random selection: This was gnarly. The random questions are stored as a filter meaning some involved computation is required to check each one for a given question. I've tried to restrict the number of checks as much as possible and there is some caching involved so performance should be fine in most cases. If …
> Iss1393 - Issues with response analysis page

- api/public/cors.php
- api/public/stackshared.php
- api/util/StackQuestionLoader.php
- tests/api_controller_test.php
- tests/api_stackquestionloader_test.php
- tests/fixtures/apifixtures.class.php
- Add defaults for everything in the API question loader. It should now be possible for the API to fill in the blanks if a partial XML file is used. If there are no inputs, a single algebraic input will be created. If there are no PRTs a single AlgEquiv node will be created.
- Fix bug where API could not access the STACK library after previous code tidy.
> Api defaults basic

- stack/mathsoutput/mathsoutputoumaths.class.php
Hi Chris,
We noticed the issue using oumaths filter with Moodle 4.5, as now the filters are moved to be in namespaced class filter_name\text_filter. Could you please review?
I have verified that its been fixed for tex and mathjax filters.
Thanks,
Anu
> Fix to update interaction with oumaths text filters for Moodle 4.5

- backup/moodle2/backup_qtype_stack_plugin.class.php
- backup/moodle2/restore_qtype_stack_plugin.class.php
- questiontype.php
- tests/restore_test.php
#1422 
- Changes also fix apparent issues with backing up of node descriptions and prt firstnodename.
- I've created our own version of the test to make sure it works with some more complex questions.
- I figured out the proper way to avoid making changes to questiontype->get_question_options() in the end.
- Worth checking hard there's no way the new convert_backup_to_questiondata() method can throw an error because a restore failing would be much worse than some duplicate questions.
> ISS1422 - Moodle core unit test failures on restore

- stack/cas/castext2/blocks/textdownload.block.php
- stack/input/inputbase.class.php
- stack/questionlibrary.class.php
#1436
- Add dummy link for textdownload blocks when rendering in STACK library (i.e. when there's no question attempt).
- Correct type of tavalue for inputs from array to string.
> iss1436 - Question library fixes

- mobile.css
- styles.css
If you nest a list inside a "helm_parts" list, the styling is applied to the inner list by mistake:
This fixes the CSS so that the styling only applies to the list items at the top level:
> helm_parts styling should only apply to top-level list items

- .github/workflows/moodle-ci.yml
- adminui/dependencies.php
- edit_stack_form.php
- question.php
- tests/editform_test.php
- Add warnings back in. Previously triggered error no longer exists. However, some reworking done to avoid similar issues where fields haven't been instantiated.
- Fixes to the dependencies page with counting of compiled questions and display of todo questions.
- Switch editor to plain text for fields that look like they have scripts but the user has the default editor and the filed is set to HTML.
> Question editing enhancements

- api/controller/RenderController.php
- api/docker/Dockerfile
- api/public/stackshared.php
- stack/input/equiv/equiv.class.php
- stack/input/notes/notes.class.php
- stack/input/textarea/textarea.class.php
- stack/input/varmatrix/varmatrix.class.php
- Use correct response rather than ta for API sample solution so it is evaluated properly e.g. `dispsf(tv,2)*m/s` becomes `(0.50*m)/s` rather than `(displaydp(0.5,2)*m)/s`.
- Remove `get_api_solution()` for some inputs as no longer needed.
- Replace line breaks with `<br>` on front end.
- Update the Debian version of the Docker container so CertBot works.
> API - Use better 'can be typed as' solution. Update Debian.

- api/README.md
- api/controller/RenderController.php
- api/dtos/StackRenderResponse.php
- question.php
- stack/cas/castext2/block.interface.php
- stack/cas/castext2/blocks/adapt.block.php
- stack/cas/castext2/blocks/adaptauto.block.php
- stack/cas/castext2/blocks/adaptbutton.block.php
- stack/cas/castext2/blocks/body.block.php
- stack/cas/castext2/blocks/cors.block.php
- stack/cas/castext2/blocks/geogebra.block.php
- stack/cas/castext2/blocks/hint.block.php
- stack/cas/castext2/blocks/iframe.block.php
- stack/cas/castext2/blocks/javascript.block.php
- stack/cas/castext2/blocks/jsxgraph.block.php
- stack/cas/castext2/blocks/parsons.block.php
- stack/cas/castext2/blocks/reveal.block.php
- stack/cas/castext2/blocks/root.specialblock.php
- stack/cas/castext2/blocks/script.block.php
- stack/cas/castext2/blocks/textdownload.block.php
- tests/api_controller_test.php
https://github.com/IDEMSInternational/pretext/issues/3
Indicate if a question has interactive elements that make a printed version make no sense.
- Add `isinteractive` static variable to stack_cas_castext2_block.
- Updated on question compile if any blocks are interactive.
- Add flag to compiledcache.
- Pass flag as part of render response from API.
~~TODO - classification of body, escape, iframe blocks.~~
@geoo89 @sangwinc
> Add static flag to API question render response

- backup/moodle2/restore_qtype_stack_plugin.class.php
This PR addresses #1431 / [MDL-83541](https://tracker.moodle.org/browse/MDL-83541). For developer information see here: https://moodledev.io/docs/5.0/apis/plugintypes/qtype/restore
This PR fixes `restore_qtype_stack_plugin::convert_backup_to_questiondata()`. Before this PR, additional question data (`inputs`, `prts`, and `deployedseeds`) were falsely loaded as sub-objects of `$questiondata->options` instead of loading them into `$questiondata` directly. The latter is correct as indicated by [qtype_stack::get_question_options()](https://github.com/maths/moodle-qtype_stack/blob/d4a97adc408edab6acb485f94f597f3e8d073fd4/questiontype.php#L411) and many other occurrences. This resulted in identical questions not being identified as such during a restore operation, causing identical questions to …
> MDL-83541: Fix loading of backup data into questiondata object in restore_qtype_stack_plugin::convert_backup_to_questiondata()

- tests/behat/analysis.feature
Hi Chris, 
When running Behat tests, our CI reports a warning about duplicate scenario names within the same feature file. And probably because of this it sometimes randomly fails on our CI server too. As each scenario in a feature file should have a unique name, I have renamed the scenarios. Could you please review?
Thanks,
Anupama
> Stack: Rename duplicate scenario names

- stack/maxima/stackmaxima.mac
- stack/options.class.php
- tests/cassession2_test.php
#1474 
- Change id string for inverse trig option from arccos-arcosh to arsinh so it fits in the DB field.
- Also change option on dropdown to arsinh(x) to match.
> iss1474 - Fix inverse trig option

- stack/maxima/assessment.mac
With simp=false this condition in poly_equate_coeffsp() is always false.
> Bug in poly_equate_coeffsp() with simp=false

- edit_stack_form.php
iss1519
Put the 'Save and continue' and 'Preview' buttons in a sticky footer.
(Trying to add the 'Save' and 'Cancel' buttons as well proved tricky - I couldn't do it without copies of all four buttons in their current location as well as in the footer.)
> iss1519 - Add sticky footer

- api/public/stackshared.php
The regular expression for feedback tag capturing sometimes fails, for example for the question below:
[Proof-by-contraposition.zip](https://github.com/user-attachments/files/21770956/Proof-by-contraposition.zip)
Paste the content of the file into the XML field in `stack.php`, and display the question.
The question renders like this:
The issue is that the function `replaceFeedbackTags` uses a greedy regex `text.match(/\[\[feedback:.*\]\]/g);` to match feedback tags, yielding the following matches:
```
[​
"[[feedback:prt1]]",
​ `[[feedback:prt2]] <br />Therefore <input type="text" name="q1_stackapi_input_ans4" id="q1_stackapi_input_ans4" size="8.8" style="width: 7.3em" autocapitalize="none" spellcheck="false" class="algebraic" value="y^? + y*x^?&gt; x^? + ?*y^?" />, <span …
```
> Fix bug in JS code of STACK API rendering

- stack/bulktester.class.php
Additional fix for #1542 to fix running tests on the rest of the current category and remaining categories in the context.
> iss1542 - Fix looping issue.

- doc/en/CAS/Numbers.md
- stack/maxima/numericaltest.mac
- tests/fixtures/answertestfixtures.class.php
Remove inert numerical wrappers in ATNumRelative and ATNumAbsolute. #1562.
> Fix to issue #1562: Remove inert numerical wrappers in ATNumRelative and ATNumAbsolute

- mobile.css
- styles.css
#1509 Make first list item appear on same line as item identifier and vertically align the identifier at the top.
We still potentially end up with an unwanted single space on the first line between the identifier and the item but that's dependent on the layout of the question HTML. The paragraph tag either needs to be on the same line hard against the list item tag or the first item needs to not be in paragraph tags. There's no real way around that with CSS without risking breaking something else.
> Iss1509 - HELM list item CSS fix

- mobile.css
- styles.css
#1601 
Looks like a combo of Bootstrap and Moodle changes have made select tags `display: block'. This update to our CSS hopefully overrides without affecting anything else. Is there any likely question set up that is worth checking in addition to the question supplied?
(CI failure is just the language pack not loading for Behat on main again.)
> iss1601 - Make select in-line
