- doc/en/CAS/Optimising_Maxima.md
I built a fresh instance of Ubuntu 14.04.04 LTS using Vagrant. Then applied this script. It compiled without errors.
> added build notes for maxima on Ubuntu

- stack/input/dropdown/dropdown.class.php
- stack/utils.class.php
Chris, your fix for this does things differently, but I needed this now and do believe this causes way less complications...
> Fix #203, by handling strings before array splits and doing some unescaping.

- doc/en/Authoring/Units.md
- stack/maxima/stackmaxima.mac
- stack/maxima/stackunits.mac
- tests/answertest_general_cas_test.php
- tests/answertestfixtures.class.php
- version.php
> Abacus 1.3.1

- stack/maxima/stackmaxima.mac
- tests/cassession_test.php
- version.php
> Abacus 1.3.2

- stack/cas/casstring.class.php
- stack/potentialresponsetree.class.php
- stack/utils.class.php
- tests/casstring_test.php
- tests/stack_utils_test.php
Remove safety measure that does not protect from the thing it tries to protect from but causes difficulties for new use-cases. Issue #225
> Allow forbidden words inside strings, #225

- doc/en/CAS/Maxima.md
function exdowncase(ex) is/ was mentioned twice
> update maxima.md, remove duplicate exdowncase(ex)

- doc/en/Installation/index.md
Makes it easier to copy and paste into a terminal.
> Put command-line commands in separate code blocks

- doc/en/Authoring/Answer_tests.md
It wasn't at all clear from the docs what the "Diff" answer test does, so I've investigated and then had a go at expanding the relevant section in the docs.
I also added a bit to the "Int" section, because that doesn't actually say how the test is passed.
> Explain what the Diff and Int answer tests do

- doc/en/Authoring/Testing.md
- doc/en/Developer/Running_question_tests_other_site.md
- doc/en/Installation/Testing_installation.md
I just thought I would give you a chance to review this Chris, before I put it on master.
> Document how to test questions from another Moodle site (hacky) #279

- healthcheck.php
- lang/en/qtype_stack.php
- stack/cas/installhelper.class.php
Added lines to update the config cache to match the db.
> Fix for issue #327

- settings.php
- Pluggable platform support
- Better support for Microsoft Windows.
- Optimisation support for MS Windows, including clisp.
- Write-through caching of settings to avoid bugs during optimisation.
- Settings for controlling Lisp dialact, execution timeout, optimising
command, batch file bypass.
- Settings are sanity checked on settings form, giving warnings and
errors.
- critical settings are timestamped against generated files, regenerating
or prompting for regen.
- feedback on optimisation.
> iss332a: Major reworking of platform and settings:

- doc/en/Authoring/Future_proof.md
Some guidelines that might be useful for other STACK users might be nice to include in the STACK documentation.
I don't think I will come up with anything more for this so maybe it could be merged so that others may give more comments.
> Guidelines

- replacedollars.php
The fix is just copied from bluktest.php.
> Fix replacedollars script for quiz contexts #322

- doc/es/Authoring/Authoring_quick_start_2.md
I hope this request is for the right es_mx branch
> Translate Authoring quick start 2

- doc/en/CAS/STACK-Maxima_sandbox.md
- stack/maxima/sandbox.wxm
Improves the sandbox setup instructions. Fixes #464
> Instructions clarified and paths corrected

- doc/en/Authoring/Authoring_quick_start.md
Thank you very much for the clarification and your fast response.
If I understood it correctly TAns still needs a factor 3 for the answer test to work correctly, so I added the differentiation of the inner function 3*x-2 to match with SAns = diff(ans1,x) in Node 2.
> RE: Clarify the author quick-start guide.

- questiontype.php
- renderer.php
- tests/walkthrough_adaptive_test.php
> STACK breaks if Moodle option 'forceclean' is turned on (e.g. View as Student)

- doc/en/Installation/index.md
> Added notice about DB case sensitivity issue

- stack/maxima/stackmaxima.mac
This is of order n^2 and serves our purposes as needed with school level maths.
> Added a mode function to the list of maxima functions

- doc/en/Students/Equivalence_reasoning.md
Very minor detail corrected (and learned how to launch a pull request -- yeah!).
> Edge cases: corrected wrong statement about none

- mkdocs.yml
- site_overrides/main.html
This fixes issues with the online docs where the search bar was invisible and where directory urls were not being used, leading to broken links.
> Fix search and linking issues on online docs

- adminui/answertests.php
- adminui/studentinputs.php
- tests/behat/create_preview_edit.feature
- tests/behat/restore_demo.feature
I think these two scripts would also benefit form progressive output.
> Add NO_OUTPUT_BUFFERING to two more scripts

- stack/utils.class.php
- tests/stack_utils_test.php
Hi Chris, this is the fix for the issue I reported this morning.
We are in a period of testing and bug-fixing at the OU right now, so if you are able to hit the  merge button relatively soon, that would help us. Thanks.
> Fix alt-text checking #770

- styles.css
I also dealt with some errors and warnings the PHPStorm spotted.
> blockquote CSS rule must be scoped to only affect STACK

- doc/en/Authoring/Equivalence_reasoning.md
- doc/en/Installation/index.md
I hope I got all the things that need to be done
> how to update

- tests/behat/create_preview_edit.feature
- tests/behat/restore_demo.feature
- tests/behat/validation_no_maths_in_question.feature
- tests/behat/xml_import.feature
Well, partially fix them. Step in the right direction.
> Update Behat tests to work with 4.0

- stack/cas/connector.server.class.php
This seems to work. Since the healthcheck page include MaximaPool calls both with, and without plots, I think checking that page is a sufficient test.
> Update server connection zip handling to non-deprecated library

- tidyquestion.php
Added include vle_specific.php, as it was needed for stack_determine_moodle_version()
Added support to Moodle version < 400, when calling question_preview_url()
> Add support for Moodle version < 400

- doc/en/CAS/Maxima.md
There should only be one h1 on the page
> Fix headings in Maxima.md

- doc/en/Authoring/CASText.md
- doc/en/CAS/Simplification.md
I expanded on the details using suggestions from https://github.com/maths/moodle-qtype_stack/issues/849
@aharjula - please correct me if I've said anything wrong!
> add more details about selective simplification in CASText #849

- questiontestrun.php
Hi Chris,
I have made a small change to fix the theme issue where there was a mismatch between number of table header columns and the number of table data columns in 'Question tools and deployed variants' tool.
Could you please review?
Thanks,
Anupama
> Fix theme issue for Question tests & deployed variants

- doc/ja/AbInitio/index.md
This PR includes a Japanese translation of AbInitio index,
I am a student assisting Prof. Nakayama.
> Japanese translation of AbInitio index

- styles.css
> add vertical alignment to inline block feedback

- api/config_sample.txt
- api/emulation/MoodleEmulation.php
- tests/vle_specific_test.php
- vle_specific.php
#1160 Use the existing MathJax filter URL setting
> Iss1160 - Remove hardcoding of MathJax URL

- stack/maxima/assessment.mac
- tests/castext_test.php
Chris, this is my first pull request, apart from the typos. Feel free to correct. Especially with the PHP part of STACK, I'm not so sure yet. I'm happy to receive tips on content and style and I'm keen to learn for future pull requests.
> decimalplaces(ex,n) for n=0 or integerp(ex); two test cases

- doc/en/Authoring/Multiple_choice_questions.md
This change adds to the documentation to show how partial marking can be done for MCQs
> Update Multiple_choice_questions.md to include partial marking

- .github/workflows/moodle-ci.yml
- lang/en/qtype_stack.php
- question.php
#1249 Downside of doing this here is that user-generated tests are not run. Are we in danger of masking a more pressing problem if users don't get round to pruning files?
> Iss1249 - Add file size check in bulk test

- mobile.css
App only CSS change - textareas were appearing completely black on Coulomb.
> iss1211 - Fix textareas in app

- stack/input/varmatrix/varmatrix.class.php
> iss1291 - Fix varmatrix with decimal commas

- stack/maxima/contrib/validators.mac
- stack/maxima/contrib/validators_test.mac
> Issue #1243: reinstate nofunctions validator code.

- doc/en/AbInitio/Authoring_quick_start_1.md
- doc/en/AbInitio/Authoring_quick_start_2.md
- doc/en/Developer/Development_track.md
- edit_stack_form.php
Change the default values for a new question to reduce the amount typed in for a minimum viable question.  This should simplify authoring of basic STACK materials.
> Edit defaults

- doc/en/Authoring/Inputs/Input_options.md
The extra option "feedback" is missing in the overview table
> feedback is missing in overview

- .github/workflows/moodle-ci.yml
- stack/input/factory.class.php
- stack/input/inputbase.class.php
- tests/caskeyval_test.php
That last code tidy pull request got merged slightly faster than I was expecting! I've now double-checked all the changes.
This pull request improves a small number and enables the behat tests for the Moodle app on MOODLE_405_STABLE.
> Code tidy tweaks

- tests/behat/library.feature
Fixes suddenly failing behat test on Moodle 5.
> ci-again - Fix behat test

- doc/en/Authoring/Inputs/Input_options.md
- doc/en/Developer/Development_track.md
- stack/input/checkbox/checkbox.class.php
- stack/input/dropdown/dropdown.class.php
- tests/input_checkbox_test.php
- tests/input_dropdown_test.php
- tests/input_radio_test.php
> Fix for issue #1323

- stack/cas/casstring.units.class.php
- tests/fixtures/answertestfixtures.class.php
- tests/input_units_test.php
> fix to issue #1359: add Dioptre as extra units.

- doc/en/Topics/Linear_algebra/Linear_algebra_core.md
- doc/en/Topics/Linear_algebra/Vector_space.md
- doc/en/Topics/Linear_algebra/Vectors.md
First block of doc edits for #1403. 
- Significant re-write of `Linear_algebra_core.md` 
- Several changes to `Vectors.md` 
- Started and finished `Vector_space.md`
> Iss1403 doc edits

- api/public/bulktest.php
- Found some issues with displaying general errors in the API bulk test and not hiding errors from previous runs.
> apibulktest - Fix some display issues

- templates/questionfolder.mustache
- templates/questionlibrary.mustache
- templates/questionreport.mustache
- tests/input_dropdown_test.php
- Fix collapsible sections in HTML broken by change to Bootstrap 5 in main.
- Fix unit tests broken by addition of an extra class to select tags in main.
> Bootstrap5

- adminui/caschat.php
- edit_stack_form.php
- lang/en/qtype_stack.php
- tests/behat/caschat.feature
- tests/behat/library.feature
#1337 
- Send the user to the edit page if they want to save their changes as a new version.
- Add tooltip and text to CASChat page.
- Add behat test.
> Iss1337 - Save as new version from CASchat

- api/composer.lock
- api/docker/docker-compose.yml
- api/public/sample.php
- api/public/stack.php
- api/public/stackshared.php
- api/util/StackQuestionLoader.php
- Update dependencies.
- Deal with defaults for a STACK information question.
- Deal with display of info questions on sample page.
> Api tweaks

- stack/bulktester.class.php
- tests/bulktester_test.php
#1419 
- Update SQL to use Moodle LIKE wrapper.
- Add unit test for method (which means we've tested on mariadb and postgres).
> iss1419 - Update todo search

- stack/maxima/stacktex.lisp
- stack/maxima/validator.mac
- tests/fixtures/inputfixtures.class.php
- tests/input_units_test.php
> Fix to issue #1331.

- doc/en/Topics/Linear_algebra/Eigen.md
- doc/en/Topics/Linear_algebra/Linear_algebra_core.md
- doc/en/Topics/Linear_algebra/Matrix_factorisation.md
- doc/en/Topics/Linear_algebra/Matrix_library.md
- doc/en/Topics/Linear_algebra/Random_Matrices.md
- doc/en/Topics/Linear_algebra/Vector_geometry.md
- doc/en/Topics/Linear_algebra/Vector_space.md
- doc/en/Topics/Linear_algebra/index.md
- Added links to source code for each of the files
- Added some extra links to point readers to other related articles where useful
- Fixed a bunch of formatting errors and typos.
> A collection of small fixes to the documentation on the new linear algebra and random matrix contributed files

- doc/en/Authoring/Answer_Tests/Equivalence.md
- stack/maxima/assessment.mac
- tests/fixtures/answertestfixtures.class.php
Fix algebraic_equivalence by reducing timeouts.  Fix to issue #1453.
> Fix algebraic_equivalence by reducing timeouts.  Fix to issue #1453.

- doc/de/index.md
These docs are out of date and we've not been able to contact the authors.
> Fixes #1505: removes German doc

- cli/bulktestall.php
- stack/bulktester.class.php
> iss1542 - Fix bulktestall restart

- tests/questiontype_test.php
Update test to deal with deprecated and replaced method.
> xmlize issue

- adminui/healthcheck.php
> Fix Undefined array key "details"

- lang/en/qtype_stack.php
- stack/cas/parsingrules/050_no_chained_inequalities.filter.php
- tests/input_algebraic_test.php
Improve specificity of message for chained inequalities.  Fixes #1602.
> Improve specificity of message for chained inequalities.  
